global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'client-service'
    static_configs:
      - targets: ['client-service:3002']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3001']

  - job_name: 'coffee-service'
    static_configs:
      - targets: ['coffee-service:3003']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3004']
